when:
  - event: manual
  - event: [push, pull_request]
    branch: main
  - event: tag

steps:
  - name: ruff
    image: ghcr.io/astral-sh/uv:python3.14-alpine@sha256:2d328eb17f7d6a8c3996d2de739e78b18c96a6b89ce72ee665a4aa06088ac629
    commands:
      - uv sync --frozen
      - uv run ruff check .
      - uv run ruff format --check .
