when:
  - event: [push, pull_request]
    branch: main

steps:
  - name: ruff-check
    image: ghcr.io/astral-sh/uv:python3.13-bookworm
    commands:
      - uv sync --frozen
      - uv run ruff check .

  - name: ruff-format
    image: ghcr.io/astral-sh/uv:python3.13-bookworm
    commands:
      - uv run ruff format --check .
