when:
  - event: manual
  - event: [push, pull_request]
    branch: main

steps:
  - name: ruff
    image: ghcr.io/astral-sh/uv:python3.13-alpine@sha256:6e2a6c29c5d6e2e99479a2b8a4f14e717e3403a5e49631800466bbdd2a878929
    commands:
      - uv sync --frozen
      - uv run ruff check .
      - uv run ruff format --check .
